language: node_js

node_js:
#  - "0.11"
  - "0.10"
#  - "0.8"
#  - "0.6"

before_install:
  - wget http://www.aerospike.com/community_downloads/3.0.39/aerospike-community-server-3.0.39-ubuntu12.04.tgz
  - tar -xf aerospike-community-server-3.0.39-ubuntu12.04.tgz
  - sudo dpkg --install aerospike-community-server-3.0.39-ubuntu12.04/aerospike-community-server-3.0.39.ubuntu12.04.x86_64.deb
  - wget http://www.aerospike.com/client_downloads/c/3.0.30/aerospike-client-c-3.0.30.ubuntu12.04.x86_64.tgz
  - tar -xf aerospike-client-c-3.0.30.ubuntu12.04.x86_64.tgz
  - sudo dpkg --install aerospike-client-c-3.0.30.ubuntu12.04.x86_64/aerospike-client-c-devel-3.0.30.ubuntu12.04.x86_64.deb
  - sudo sed -i 's/address any/address 127.0.0.1/' /etc/aerospike/aerospike.conf
  - sudo /etc/init.d/aerospike start
  - sleep 20
  - date
  - sudo tail -100 /var/log/aerospike/aerospike.log
  - ifconfig

install:
  - npm install
  - npm test

